# Configuración conexión a clúster

spring.application.name=discografia
spring.data.mongodb.uri=mongodb+srv://rodrigoas4nchez_db_user:"CONTRASEÑA"@eva-u2-spring.jrjpioy.mongodb.net/?appName=eva-u2-spring
spring.data.mongodb.database=discografica-db
